name = "mcp-server-cloudflare"
main = "src/combined.app.ts" # Assuming you build your TS to JS
compatibility_date = "2025-03-10" # Use the latest compatibility_date across all sub-apps
compatibility_flags = ["nodejs_compat"]
environment = "production" # Add this line

[observability.logs]
enabled = true

# =========================================================================
# Production Environment Configuration
# All bindings, variables, and migrations are defined within this section.
# =========================================================================
[env.production]
name = "mcp-server-cloudflare-production"
account_id = "b3304b14848de15c72c24a14b0cd187d" # Consistent account ID from sub-app production configs
routes = [{ pattern = "mcp-server-cloudflare.hacolby.workers.dev", custom_domain = true }] # Example combined domain

# Durable Objects Bindings - Consolidated from all sub-application production configs
[env.production.durable_objects]
bindings = [
  # From browser-rendering
  { class_name = "BrowserMCP", name = "BROWSER_MCP_DO" },

  # From docs-vectorize
  { class_name = "CloudflareDocumentationMCP", name = "DOCS_MCP_DO" },

  # From sandbox-container
  { class_name = "ContainerMcpAgent", name = "SANDBOX_MCP_DO" },
  { class_name = "ContainerManager", name = "CONTAINER_MANAGER_DO" },
  { class_name = "UserContainer", name = "USER_CONTAINER_DO" },

  # From workers-bindings
  { class_name = "WorkersBindingsMCP", name = "BINDINGS_MCP_DO" },
  # UserDetails is listed once below

  # From workers-builds
  { class_name = "BuildsMCP", name = "BUILDS_MCP_DO" },
  # UserDetails is listed once below

  # From workers-observability
  { class_name = "ObservabilityMCP", name = "OBSERVABILITY_MCP_DO" },

  # Shared UserDetails Durable Object (used by browser, bindings, builds, observability)
  { class_name = "UserDetails", name = "USER_DETAILS_DO" }
]

# AI Binding - Consolidated
[env.production.ai]
binding = "AI"

# Vectorize Bindings - Consolidated
[[env.production.vectorize]]
binding = "VECTORIZE"
index_name = "docs-bge-base"

# KV Namespaces - Consolidated (using IDs found in production envs of sub-apps)
# Note: If there are conflicts or specific needs for different KV IDs for the same binding
# across sub-apps in production, you would need to adjust this,
# or create separate KV bindings and map them in combined.app.ts.
# Here, we picked representative production IDs from your sub-apps.
[[env.production.kv_namespaces]]
binding = "OAUTH_KV"
id = "8d66696bdd534133bbc6a773b8caf99b" # Example: From sandbox-container production
[[env.production.kv_namespaces]]
binding = "USER_BLOCKLIST"
id = "b874d6ae29ec43e5afad7be8da067676" # Example: From sandbox-container production

# Container Bindings - From sandbox-container production
[[env.production.containers]]
name = "sandbox-container"
image = "registry.cloudchamber.cfdata.org/sandbox-container:d802004" # Production image from sandbox-container
class_name = "UserContainer"
max_instances = 50 # Max from sandbox-container production
rollout_step_percentage = 100
instances = 10 # Instances from sandbox-container production

# Analytics Engine Datasets - Consolidated
[[env.production.analytics_engine_datasets]]
binding = "MCP_METRICS"
dataset = "mcp-metrics-production"

# Variables - Consolidated
[env.production.vars]
ENVIRONMENT = "production"
MCP_SERVER_NAME = "mcp-server-cloudflare-production" # Name for the combined worker
MCP_SERVER_VERSION = "1.0.0" # Version for the combined worker
CLOUDFLARE_CLIENT_ID = "<YOUR_CLOUDFLARE_CLIENT_ID>" # Retain placeholder if not filled
CLOUDFLARE_CLIENT_SECRET = "<YOUR_CLOUDFLARE_CLIENT_SECRET>" # Retain placeholder if not filled
GIT_HASH = "OVERRIDEN_DURING_DEPLOYMENT" # From workers-builds/observability production
SENTRY_DSN = "https://2cc5007c2ad5f33e9be007d4b40208ef@sentry10.cfdata.org/1793" # Example: From workers-builds production

# Migrations - Consolidated (ensure tags are unique and in correct order)
# These are applied to the Durable Objects declared within this production environment.
[[env.production.migrations]]
tag = "v1_browser"
new_sqlite_classes = ["BrowserMCP"]

[[env.production.migrations]]
tag = "v1_docs"
new_sqlite_classes = ["CloudflareDocumentationMCP"]

[[env.production.migrations]]
tag = "v1_sandbox_manager_agent"
new_sqlite_classes = ["ContainerManager", "ContainerMcpAgent"]

[[env.production.migrations]]
tag = "v2_sandbox_user_container"
new_sqlite_classes = ["UserContainer"]

[[env.production.migrations]]
tag = "v1_bindings_user_details"
new_sqlite_classes = ["WorkersBindingsMCP", "UserDetails"]

[[env.production.migrations]]
tag = "v1_builds"
new_sqlite_classes = ["BuildsMCP"]

[[env.production.migrations]]
tag = "v1_observability"
new_sqlite_classes = ["ObservabilityMCP"]
