name = "mcp-server-cloudflare"
main = "dist/worker.js"
compatibility_date = "2025-04-03"
compatibility_flags = ["nodejs_compat"]

[observability.logs]
enabled = true

[durable_objects]
bindings = [
  { class_name = "BrowserMCP", name = "BROWSER_MCP_DO" },
  { class_name = "CloudflareDocumentationMCP", name = "DOCS_MCP_DO" },
  { class_name = "ContainerMcpAgent", name = "SANDBOX_MCP_DO" },
  { class_name = "ContainerManager", name = "CONTAINER_MANAGER_DO" },
  { class_name = "UserContainer", name = "USER_CONTAINER_DO" },
  { class_name = "WorkersBindingsMCP", name = "BINDINGS_MCP_DO" },
  { class_name = "BuildsMCP", name = "BUILDS_MCP_DO" },
  { class_name = "ObservabilityMCP", name = "OBSERVABILITY_MCP_DO" },
  { class_name = "UserDetails", name = "USER_DETAILS_DO" },
]

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "docs-bge-base"

[[kv_namespaces]]
binding = "OAUTH_KV"
id = "DEV_KV"

[[kv_namespaces]]
binding = "USER_BLOCKLIST"
id = "DEV_BLOCKLIST"

[[containers]]
name = "sandbox-container"
image = "../sandbox-container/Dockerfile"
class_name = "UserContainer"
max_instances = 2
rollout_step_percentage = 100

[[analytics_engine_datasets]]
binding = "MCP_METRICS"
dataset = "mcp-metrics-dev"

[vars]
ENVIRONMENT = "development"
MCP_SERVER_NAME = "<PLACEHOLDER>"
MCP_SERVER_VERSION = "<PLACEHOLDER>"
CLOUDFLARE_CLIENT_ID = "<PLACEHOLDER>"
CLOUDFLARE_CLIENT_SECRET = "<PLACEHOLDER>"

[[migrations]]
tag = "v1_docs"
new_sqlite_classes = ["CloudflareDocumentationMCP"]

[[migrations]]
tag = "v1_sandbox_manager_agent"
new_sqlite_classes = ["ContainerManager", "ContainerMcpAgent"]

[[migrations]]
tag = "v2_sandbox_user_container"
new_sqlite_classes = ["UserContainer"]

[[migrations]]
tag = "v1_browser"
new_sqlite_classes = ["BrowserMCP"]

[[migrations]]
tag = "v1_bindings"
new_sqlite_classes = ["WorkersBindingsMCP"]

[[migrations]]
tag = "v1_builds"
new_sqlite_classes = ["UserDetails", "BuildsMCP"]

[[migrations]]
tag = "v1_observability"
new_sqlite_classes = ["UserDetails", "ObservabilityMCP"]

[dev]
port = 8787

[env.staging]
name = "mcp-server-cloudflare-staging"
account_id = "6702657b6aa048cf3081ff3ff3c9c52f"
routes = [
  { pattern = "browser-staging.mcp.cloudflare.com", custom_domain = true },
  { pattern = "docs-staging.mcp.cloudflare.com", custom_domain = true },
  { pattern = "containers-staging.mcp.cloudflare.com", custom_domain = true },
  { pattern = "bindings-staging.mcp.cloudflare.com", custom_domain = true },
  { pattern = "builds-staging.mcp.cloudflare.com", custom_domain = true },
  { pattern = "observability-staging.mcp.cloudflare.com", custom_domain = true },
]

[env.staging.durable_objects]
bindings = [
  { class_name = "BrowserMCP", name = "BROWSER_MCP_DO" },
  { class_name = "CloudflareDocumentationMCP", name = "DOCS_MCP_DO" },
  { class_name = "ContainerMcpAgent", name = "SANDBOX_MCP_DO" },
  { class_name = "ContainerManager", name = "CONTAINER_MANAGER_DO" },
  { class_name = "UserContainer", name = "USER_CONTAINER_DO" },
  { class_name = "WorkersBindingsMCP", name = "BINDINGS_MCP_DO" },
  { class_name = "BuildsMCP", name = "BUILDS_MCP_DO" },
  { class_name = "ObservabilityMCP", name = "OBSERVABILITY_MCP_DO" },
  { class_name = "UserDetails", name = "USER_DETAILS_DO" },
]

[env.staging.ai]
binding = "AI"

[[env.staging.vectorize]]
binding = "VECTORIZE"
index_name = "docs-bge-base"

[[env.staging.kv_namespaces]]
binding = "OAUTH_KV"
id = "a6ad24203a244d248f2fe1acfeb7b3a3"

[[env.staging.kv_namespaces]]
binding = "USER_BLOCKLIST"
id = "68e95343ded8448db179256c68f175b2"

[[env.staging.containers]]
name = "sandbox-container-staging"
image = "registry.cloudchamber.cfdata.org/sandbox-container:d802004"
class_name = "UserContainer"
max_instances = 5
rollout_step_percentage = 100
instances = 3

[[env.staging.analytics_engine_datasets]]
binding = "MCP_METRICS"
dataset = "mcp-metrics-staging"

[env.staging.vars]
ENVIRONMENT = "staging"
MCP_SERVER_NAME = "<PLACEHOLDER>"
MCP_SERVER_VERSION = "1.0.0"
CLOUDFLARE_CLIENT_ID = "<PLACEHOLDER>"
CLOUDFLARE_CLIENT_SECRET = "<PLACEHOLDER>"

[env.production]
name = "mcp-server-cloudflare-production"
account_id = "6702657b6aa048cf3081ff3ff3c9c52f"
routes = [
  { pattern = "browser.mcp.cloudflare.com", custom_domain = true },
  { pattern = "docs.mcp.cloudflare.com", custom_domain = true },
  { pattern = "containers.mcp.cloudflare.com", custom_domain = true },
  { pattern = "bindings.mcp.cloudflare.com", custom_domain = true },
  { pattern = "builds.mcp.cloudflare.com", custom_domain = true },
  { pattern = "observability.mcp.cloudflare.com", custom_domain = true },
]

[env.production.durable_objects]
bindings = [
  { class_name = "BrowserMCP", name = "BROWSER_MCP_DO" },
  { class_name = "CloudflareDocumentationMCP", name = "DOCS_MCP_DO" },
  { class_name = "ContainerMcpAgent", name = "SANDBOX_MCP_DO" },
  { class_name = "ContainerManager", name = "CONTAINER_MANAGER_DO" },
  { class_name = "UserContainer", name = "USER_CONTAINER_DO" },
  { class_name = "WorkersBindingsMCP", name = "BINDINGS_MCP_DO" },
  { class_name = "BuildsMCP", name = "BUILDS_MCP_DO" },
  { class_name = "ObservabilityMCP", name = "OBSERVABILITY_MCP_DO" },
  { class_name = "UserDetails", name = "USER_DETAILS_DO" },
]

[env.production.ai]
binding = "AI"

[[env.production.vectorize]]
binding = "VECTORIZE"
index_name = "docs-bge-base"

[[env.production.kv_namespaces]]
binding = "OAUTH_KV"
id = "753f27a19ef94d7dbd49de05588ca890"

[[env.production.kv_namespaces]]
binding = "USER_BLOCKLIST"
id = "b874d6ae29ec43e5afad7be8da067676"

[[env.production.containers]]
name = "sandbox-container"
image = "registry.cloudchamber.cfdata.org/sandbox-container:d802004"
class_name = "UserContainer"
max_instances = 50
rollout_step_percentage = 100
instances = 10

[[env.production.analytics_engine_datasets]]
binding = "MCP_METRICS"
dataset = "mcp-metrics-production"

[env.production.vars]
ENVIRONMENT = "production"
MCP_SERVER_NAME = "<PLACEHOLDER>"
MCP_SERVER_VERSION = "1.0.0"
CLOUDFLARE_CLIENT_ID = "<PLACEHOLDER>"
CLOUDFLARE_CLIENT_SECRET = "<PLACEHOLDER>"
